---

name: Sensorium
options:
  bundleIdPrefix: net.hisaac
  useTabs: true
  tabWidth: 4
  deploymentTarget:
    macOS: 13.0
  groupSortPosition: top

packages:
  SwiftLint:
    url: https://github.com/realm/SwiftLint
    from: 0.54.0

targets:

  SensoriumApp:
    templates: [base]
    type: application
    dependencies:
      - target: SensoriumKit

  SensoriumCLI:
    templates: [base]
    type: tool
    dependencies:
      - target: SensoriumKit

  SensoriumKit:
    templates: [base]
    type: framework

targetTemplates:
  base:
    platform: macOS
    sources: ["Sources/${target_name}"]
    buildToolPlugins:
      - plugin: SwiftLint
        package: SwiftLint
