---

name: Sensorium
options:
  bundleIdPrefix: net.hisaac
  useTabs: true
  tabWidth: 4
  deploymentTarget:
    macOS: 13.0
  groupSortPosition: top
  postGenCommand: scripts/set-local-derived-data.sh Sensorium.xcodeproj

fileGroups:
- .github
- .gitignore
- .swiftlint.yml
- .xcode-version
- Configs
- justfile
- LICENSE
- NOTES.md
- project.yml
- README.md
- scripts
- Sources

configFiles:
  Debug: Configs/Project.Debug.xcconfig
  Release: Configs/Project.Release.xcconfig

packages:
  SwiftLint:
    url: https://github.com/realm/SwiftLint
    from: 0.54.0
  VerifyNoBuildSettings:
    path: Packages/VerifyNoBuildSettings

targets:

  Sensorium:
    templates: [base]
    type: application
    dependencies:
      - target: SensoriumKit
    entitlements:
      path: Sources/${target_name}/Resources/${target_name}.entitlements

  SensoriumCLI:
    templates: [base]
    type: tool
    dependencies:
      - target: SensoriumKit

  SensoriumKit:
    templates: [base]
    type: framework

targetTemplates:
  base:
    platform: macOS
    sources: ["Sources/${target_name}"]
    configFiles:
      Debug: Sources/${target_name}/Configs/${target_name}.Debug.xcconfig
      Release: Sources/${target_name}/Configs/${target_name}.Release.xcconfig
    buildToolPlugins:
      - plugin: SwiftLintPlugin
        package: SwiftLint
      - plugin: VerifyNoBuildSettingsPlugin
        package: VerifyNoBuildSettings
