---

name: Sensorium
options:
  bundleIdPrefix: net.hisaac
  useTabs: true
  tabWidth: 4
  deploymentTarget:
    macOS: 13.0
  groupSortPosition: top
  settings:
    ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS: YES # Recommended by Xcode
    DEAD_CODE_STRIPPING: YES # Recommended by Xcode
    ENABLE_USER_SCRIPT_SANDBOXING: NO # Needed to allow SwiftLint to run

packages:
  SwiftLint:
    url: https://github.com/realm/SwiftLint
    from: 0.54.0

targets:

  Sensorium:
    templates: [base]
    type: application
    dependencies:
      - target: SensoriumKit
    settings:
      CODE_SIGNING_ALLOWED: NO
      GENERATE_INFOPLIST_FILE: YES
      INFOPLIST_KEY_LSApplicationCategoryType: public.app-category.utilities
      INFOPLIST_KEY_NSMainNibFile: MainMenu
      INFOPLIST_KEY_NSPrincipalClass: NSApplication
    entitlements:
      path: Sources/${target_name}/Resources/${target_name}.entitlements

  SensoriumCLI:
    templates: [base]
    type: tool
    dependencies:
      - target: SensoriumKit

  SensoriumKit:
    templates: [base]
    type: framework
    settings:
      ENABLE_MODULE_VERIFIER: YES # Recommended by Xcode

targetTemplates:
  base:
    platform: macOS
    sources: ["Sources/${target_name}"]
    buildToolPlugins:
      - plugin: SwiftLintPlugin
        package: SwiftLint
